package com.oracle.mapper;

import com.oracle.web.bean.Fenlei;
import java.util.List;

public interface FenleiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenlei
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    int deleteByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenlei
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    int insert(Fenlei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenlei
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    Fenlei selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenlei
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    List<Fenlei> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenlei
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    int updateByPrimaryKey(Fenlei record);
}