package com.oracle.web.bean;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bid
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.fname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.chubanshe
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private String chubanshe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.zhuangtai
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private String zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.jieshuren
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private String jieshuren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.f_id
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private Integer fId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bid
     *
     * @return the value of book.bid
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bid
     *
     * @param bid the value for book.bid
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.fname
     *
     * @return the value of book.fname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.fname
     *
     * @param fname the value for book.fname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bname
     *
     * @return the value of book.bname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bname
     *
     * @param bname the value for book.bname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.chubanshe
     *
     * @return the value of book.chubanshe
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public String getChubanshe() {
        return chubanshe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.chubanshe
     *
     * @param chubanshe the value for book.chubanshe
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setChubanshe(String chubanshe) {
        this.chubanshe = chubanshe == null ? null : chubanshe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.zhuangtai
     *
     * @return the value of book.zhuangtai
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public String getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.zhuangtai
     *
     * @param zhuangtai the value for book.zhuangtai
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setZhuangtai(String zhuangtai) {
        this.zhuangtai = zhuangtai == null ? null : zhuangtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.jieshuren
     *
     * @return the value of book.jieshuren
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public String getJieshuren() {
        return jieshuren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.jieshuren
     *
     * @param jieshuren the value for book.jieshuren
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setJieshuren(String jieshuren) {
        this.jieshuren = jieshuren == null ? null : jieshuren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.f_id
     *
     * @return the value of book.f_id
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.f_id
     *
     * @param fId the value for book.f_id
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

	public Book(Integer bid, String fname, String bname, String price, String chubanshe, String zhuangtai,
			String jieshuren, Integer fId) {
		super();
		this.bid = bid;
		this.fname = fname;
		this.bname = bname;
		this.price = price;
		this.chubanshe = chubanshe;
		this.zhuangtai = zhuangtai;
		this.jieshuren = jieshuren;
		this.fId = fId;
	}

	public Book() {
		super();
		// TODO Auto-generated constructor stub
	}
    
    
}