package com.oracle.web.bean;

public class Fenlei {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenlei.f_id
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenlei.fname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    private String fname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenlei.f_id
     *
     * @return the value of fenlei.f_id
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenlei.f_id
     *
     * @param fId the value for fenlei.f_id
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenlei.fname
     *
     * @return the value of fenlei.fname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenlei.fname
     *
     * @param fname the value for fenlei.fname
     *
     * @mbg.generated Wed May 08 12:26:45 CST 2019
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }
}